export const ROUTES_PATHS = {
  HOME: '/',
  REGISTER_USER: '/register-user',
  LOGIN: '/login-user',
  ERROR_GENERIC: '/error-generic',
  ORDER_USER: '/order-user',
  CART: '/cart',
  ORDER_DELIVERY_STAGE: '/order-delivery-stage',
  ORDER_SUMMARY_CAKE: '/order-summary-cake',
  EDIT_ORDER: '/edit-order-details',
  PRODUCTS: '/products',
  EDIT_PRODUCT: '/products/edit/:id',
  ADD_PRODUCT: '/add-product',
  DASHBOARD: '/dashboard',
  DETAIL_ORDER: '/detail-order',
  NUMBER_GUESTS: '/number-guests',
  PROFILE: '/profile', 
};